package networking.rpcprotocol;


public enum RequestType {
    GET_BIBLIOTECAR, GET_ADMIN, GET_CARTI, GET_CARTI_BIBLIOTECAR, GET_CARTI_DUPA_CLIENT, UPDATE_CARTE, ADD_CLIENT, ADD_CARTE, DELETE_CARTE, LOG_IN_CLIENT, LOG_IN_BIBLIOTECAR, LOG_IN_ADMIN, GET_PERSON

}
